version: 2.1

#orbs:
#  go: circleci/go@1.11.0

jobs:
  build:
    docker:
      - image: cimg/go:1.20.13
    environment:
      TEST_RESULTS_DIR: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS_DIR
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
#      - go/test:
#          covermode: atomic
#          failfast: true
#          race: true
      - run:
          name: Run tests
          command: gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml

      - store_test_results:
          path: /tmp/test-results

workflows:
  main:
    jobs:
      - build