name: release

on:
#  push:
#    tags:
#      - v*.*.*
  pull_request:

jobs:

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          args: build --clean --config=.goreleaser-darwin.yml
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#  linux:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Set up Go
#        uses: actions/setup-go@v5
#        with:
#          go-version: '1.20'
#
#      - name: Run GoReleaser
#        uses: goreleaser/goreleaser-action@v5
#        with:
#          distribution: goreleaser
#          args: build --clean --config=.goreleaser-linux.yml
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#  windows:
#    runs-on: windows-latest