name: ci

on:
#  push:
#    tags:
#      - v*.*.*
  pull_request:
    branches: [ "main" ]

jobs:

#  TODO: add more OS
#  TODO: goreleaser

  release-linux-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: '~> v1'
          args: build --clean
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}